import { Router, type IRouter } from "express";
import healthRouter from "./health";
import internalSaasRouter from "./internalSaas";
import authRouter from "./auth";
import usersRouter from "./users";
import categoriesRouter from "./categories";
import uomRouter from "./uom";
import configRouter from "./config";
import vendorsRouter from "./vendors";
import ingredientsRouter from "./ingredients";
import menuItemsRouter from "./menuItems";
import purchasesRouter from "./purchases";
import expensesRouter from "./expenses";
import expenseCostTypesRouter from "./expenseCostTypes";
import inventoryRouter from "./inventory";
import wasteRouter from "./waste";
import trialsRouter from "./trials";
import dashboardRouter from "./dashboard";
import reportsRouter from "./reports";
import auditLogsRouter from "./auditLogs";
import uploadRouter from "./upload";
import settlementsRouter from "./settlements";
import pettyCashRouter from "./pettyCash";
import employeesRouter from "./employees";
import backupRouter from "./backup";
import vendorPaymentsRouter from "./vendorPayments";
import salesInvoicesRouter from "./salesInvoices";
import posIntegrationsRouter from "./posIntegrations";
import customersRouter from "./customers";
import insightsRouter from "./insights";
import decisionRouter from "./decision";
import rolesRouter from "./roles";
import notificationsRouter from "./notifications";
// ─── v2.0 New Modules ─────────────────────────────────────────────────────────
import tablesRouter from "./tables";
import kotRouter from "./kot";
import eodRouter from "./eod";
import stocktakesRouter from "./stocktakes";
import purchaseOrdersRouter from "./purchaseOrders";
import timeclockRouter from "./timeclock";
import expenseBudgetsRouter from "./expenseBudgets";
import modifiersRouter from "./modifiers";
import searchRouter from "./search";

const router: IRouter = Router();

router.use(healthRouter);
router.use(internalSaasRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(categoriesRouter);
router.use(uomRouter);
router.use(configRouter);
router.use(vendorsRouter);
router.use(ingredientsRouter);
router.use(menuItemsRouter);
router.use(purchasesRouter);
router.use(expensesRouter);
router.use(expenseCostTypesRouter);
router.use(inventoryRouter);
router.use(wasteRouter);
router.use(trialsRouter);
router.use(dashboardRouter);
router.use(reportsRouter);
router.use(auditLogsRouter);
router.use(uploadRouter);
router.use(settlementsRouter);
router.use(pettyCashRouter);
router.use(employeesRouter);
router.use(backupRouter);
router.use(vendorPaymentsRouter);
router.use(salesInvoicesRouter);
router.use(posIntegrationsRouter);
router.use(customersRouter);
router.use(insightsRouter);
router.use(decisionRouter);
router.use(rolesRouter);
router.use(notificationsRouter);
// ─── v2.0 New Modules ─────────────────────────────────────────────────────────
router.use(tablesRouter);
router.use(kotRouter);
router.use(eodRouter);
router.use(stocktakesRouter);
router.use(purchaseOrdersRouter);
router.use(timeclockRouter);
router.use(expenseBudgetsRouter);
router.use(modifiersRouter);
router.use(searchRouter);

export default router;
